baseURL = "https://chienkira.github.io/blog"
title = "Chienkira"
copyright = "" # for smart copyright line, leave this blank and check [params.copyright]

theme = "minimo"
disqusShortname = "chienkira-github-io"
googleAnalytics = "UA-135034755-1"
Paginate = 7
preserveTaxonomyNames = true
enableRobotsTXT = true # generate robots.txt
pygmentsCodefences = true # Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
enableEmoji = true
# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "chienkira | a web full stack engineer | personal blog about tech and life in Japan"
title404 = "a web full stack engineer | personal blog about tech and life in Japan"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Chien Kira"
startYear = "2019"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "2006, Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideEntryMeta = ["page"] # boolean / array of sections
showReadingTime = true
showLastmod = true
taxonomyCloudShuffle = true
accentColor = "#ffcd00"
hideMainMenu = false

[params.sidebar]
enable = true

[params.widgets]
header = ["breadcrumbs"]
homepage = ["recent_posts"]
sidebar = ["about","sidebar_menu","taxonomy_cloud"]
footer = ["social_menu"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
email = "chienhedspi@gmail.com"
facebook = "chienkira"
github = "chienkira"
instagram = "chienkira"
twitter = "chienkira"

[params.comments]
enable = true

#[params.search]
#client = "fuse" # algolia / fuse / lunr
#
#[params.search.algolia]
#appId = ""
#indexName = ""
#searchApiKey = ""

[taxonomies]
author = "chienkira"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "Home　"
weight = -100
url = "/"

[[menu.main]]
name = "All posts　"
weight = -30
url = "/posts"

[[menu.main]]
name = "My portfolio　"
weight = -20
url = "https://chienkira.github.io"

[[menu.main]]
name = "Rss　"
weight = -19
url = "/index.xml"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
